### ISSUE TITLE
CASSANDRA_COMMITLOG_DIR no longer working

### ISSUE THREAD

**Issue by LarryLiu-NetBase** [bitnami/bitnami-docker-cassandra#107]
### Name and Version

bitnami/cassandra:4.0.3-debian-10-r0

### What steps will reproduce the bug?

The variables no longer working as it's overwritten in /opt/bitnami/scripts/cassandra-env.sh from commit 
https://github.com/bitnami/bitnami-docker-cassandra/commit/8ba6b9c31492d333bb4d48f114fc23a8868b70e9

### What is the expected behavior?

Should check the if variables exist first before set the value

### What do you see instead?

CASSANDRA_COMMITLOG_DIR still set to CASSANDRA_COMMITLOG_DIR=/bitnami/cassandra/data/commitlog

**Comment by rafariossaa** [comment]
Hi,
  Thanks from spotting this out.

**Comment by rafariossaa** [comment]
Would you like to check the latest release `4.0.3-debian-10-r29` ? It should be fixed in it
