### ISSUE TITLE
Question about auth

### ISSUE THREAD

**Issue by dustinsmith1024** [bitnami/bitnami-docker-cassandra#48]
How does the user name and password work here? I am trying to figure out how it makes it into the cassandra.yml file?  I don't see anything in the entrypoint file that sets this up.  The official Cassandra docker image doesn't support user/password so I am exploring options for doing this.

**Comment by juan131** [comment]
Hi @dustinsmith1024 

As described on the [#Configuration](https://github.com/bitnami/bitnami-docker-cassandra#environment-variables) section, you can use the env. variables below to configure the user and password:

```
CASSANDRA_USER
CASSANDRA_PASSWORD
```

Those env. variables (and the rest of them) are parsed into a [inputs JSON file](https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/rootfs/cassandra-inputs.json) which is passed to [Nami](https://github.com/bitnami/nami) which is in charge of initialising Cassandra.

I know it's a little bit complex but please feel free to ask any question you may have.
