### ISSUE TITLE
Cassandra TLS is not working

### ISSUE THREAD

**Issue by sukrit007** [bitnami/bitnami-docker-cassandra#54]
**Description**
It looks like client to node and node to node TLS is not working for cassandra.  Truststore location in generated cassandra.yaml is "undefined".  As a result cassandra fails to start as it can not find truststore by name : "undefined"

**Steps to reproduce the issue:**

- Follow steps at : https://github.com/bitnami/bitnami-docker-cassandra#tls-encryption . Also set CASSANDRA_CLIENT_ENCRYPTION to true 

**Describe the results you received:**

Cassandra initialization fails.  In the cassandra logs,  there is an exception that it can not find truststore by name: "undefined".

**Describe the results you expected:**
Cassandra initialization to succeed with client to node and node to node TLS enabled.

**Additional information you deem important (e.g. issue happens only occasionally):**

It looks like there is problem with nami cassandra package.  After looking at main.js in nami package,  I noticed that truststoreLocation is misspelled: 
```
truststorelLocation: $app.truststorelLocation,
```
However,  I could not find source code for the same to send a PR.

**Version**

- Output of `docker version`:

```
Docker version 18.09.2, build 6247962
```

- Output of `docker info`:
N/A

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @sukrit007.

Thank you very much for reporting this. The code for the nami package is not published, but the issue should be solved in the following releases:

- `3.11.4-debian-9-r76`
- `3.11.4-ol-7-r89`

Can you please try it, and let us know how it goes?

Regards,
Alejandro
