### ISSUE TITLE
can't override cassandra.yaml

### ISSUE THREAD

**Issue by agprst** [bitnami/bitnami-docker-cassandra#58]
**Description**

Hello Bitnami Team, I need some help. I want to override the `cassandra.yaml`
I download the `cassandra.yaml` file as instructed in ReadMe file.
then I tried to edit the `write_request_timeout_in_ms` in the file
but it's not working
please help.

**Steps to reproduce the issue:**

1. download cassandra.yaml
`https://raw.githubusercontent.com/apache/cassandra/trunk/conf/cassandra.yaml`
2. run
`docker run --name cassandra -p 7000:7000 -e CASSANDRA_TRANSPORT_PORT_NUMBER=7000 -v /cassandra.yaml:/bitnami/cassandra/conf/cassandra.yaml:ro -v /bitnami/cassandra:/bitnami bitnami/cassandra:latest`

**Describe the results you received:**

I got this error

> cassandra 14:25:58.48 Welcome to the Bitnami cassandra container
> cassandra 14:25:58.48 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
> cassandra 14:25:58.48 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
> cassandra 14:25:58.49 Send us your feedback at containers@bitnami.com
> cassandra 14:25:58.49
> cassandra 14:25:58.49 INFO  ==> ** Starting Cassandra setup **
> cassandra 14:25:58.51 INFO  ==> Validating settings in CASSANDRA_* env vars..
> cassandra 14:25:58.51 WARN  ==> You set the environment variable CASSANDRA_PASSWORD=cassandra. This is the default value when bootstrapping Cassandra and should not be used in production environments.
> cassandra 14:25:58.53 INFO  ==> Initializing Cassandra database...
> sed: couldn't edit /opt/bitnami/cassandra/conf/cassandra.yaml: not a regular file

**Describe the results you expected:**

it can override the cassandra.yaml file

**Version**

- Output of `docker version`:

```
Docker version 19.03.5, build 633a0ea
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: AFHX:HDYM:NKZR:LRBI:DF3V:4QB5:MNWB:TWKT:Z4ZJ:AKBG:4J2O:S5OY
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 45
  System Time: 2019-11-22T14:29:30.5046028Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I use Docker for Windows

**Comment by jotamartos** [comment]
Hi, 

I just read that section in the README and it seems that there is something wrong there. You do not need to mount a "bitnami/cassandra" path inside the /bitnami folder, you simply need to mount your custom configuration file

```
docker run --name cassandra -p 7000:7000 -e CASSANDRA_TRANSPORT_PORT_NUMBER=7000 -v /path/to/cassandra.yaml:/bitnami/cassandra/conf/cassandra.yaml:ro bitnami/cassandra:latest
```

I included a test line at the end of the file and checked that the container included that line later 

```
$  cat /opt/bitnami/cassandra/conf/cassandra.yaml
...
# Test line
```

I'll open a task on our side to ensure that the information in the README is clear when mounting a custom cassandra.yaml file in the container 

Thanks

**Comment by amarrnathh** [comment]
![image](https://user-images.githubusercontent.com/74395610/109318790-2eb3b200-7874-11eb-8ec4-12046cffc479.png)
when i am giving my own config file it is saying like below please help
it is in kubernetes
cassandra 15:18:19.38
cassandra 15:18:19.39 Welcome to the Bitnami cassandra container
cassandra 15:18:19.39 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra 15:18:19.39 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra 15:18:19.39
cassandra 15:18:19.39 INFO  ==> ** Starting Cassandra setup **
cassandra 15:18:19.42 INFO  ==> Validating settings in CASSANDRA_* env vars..
cassandra 15:18:19.45 INFO  ==> Initializing Cassandra database...
rm: cannot remove '/opt/bitnami/cassandra/conf/cassandra.yaml': Read-only file system

**Comment by marcosbc** [comment]
Hi @amarrnathh, if you mount the file at `/bitnami/cassandra/conf/cassandra.yaml` instead it should work. Refer to the documentation in the README: https://github.com/bitnami/bitnami-docker-cassandra#configuration-file
