### ISSUE TITLE
How to backup and restore data from Apache Cassandra 

### ISSUE THREAD

**Issue by pratapagiri** [bitnami/bitnami-docker-cassandra#61]
We are planning to move to Bitnami Cassandra.
I'm looking for some guidance on how to backup data from Apache Cassandra and restore it in Bitnami Cassandra.

I have looked at documentation at [https://docs.bitnami.com/azure-templates/infrastructure/cassandra/administration/backup-restore/]

Can someone provide me steps to backup and restore data?

**Comment by marcosbc** [comment]
Hi @pratapagiri, the `nodetool` is available in all Apache Cassandra distributions, including Bitnami's. The steps in that guide should work for you.

If you are going to use a Docker container, you can copy files between containers in the following way:

    docker cp OLDCONTAINER:/path/to/file /tmp/
    docker cp /tmp/file NEWCONTAINER:/path/to/file

(where `OLDCONTAINER` and `NEWCONTAINER` are the old and new container names/IDs, respectively)
