### ISSUE TITLE
186 Killed

### ISSUE THREAD

**Issue by JuniorCtba** [bitnami/bitnami-docker-cassandra#64]
Hello,

I am running cassandra latest version in Openshift.

I am getting this error

cassandra 15:39:18.24 INFO  ==> Starting Cassandra
--
  | cassandra 15:39:18.24 INFO  ==> Checking that it started up correctly
  | /libos.sh: line 192:   186 Killed                  "${cmd[@]}" "${args[@]}" > "$logger" 2>&1

**Comment by JuniorCtba** [comment]
was an issue on my service

**Comment by andresbono** [comment]
Thanks for letting us know, @JuniorCtba.
