### ISSUE TITLE
[FEATURE] Allow all cassandra config options to be given as env vars (similar to bitnami/kafka image)

### ISSUE THREAD

**Issue by matthewadams** [bitnami/bitnami-docker-cassandra#67]
**Description**
The bitnami/kafka image allows arbitrary config settings via env var:  see https://github.com/bitnami/bitnami-docker-kafka/blob/998c06567bc4e13623012963dbefa24dd6c35988/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L371

Please do the same for this image using the prefix `CASSANDRA_CFG_`.

**Comment by matthewadams** [comment]
Not stale

**Comment by rafariossaa** [comment]
Hi,
This task is in our backlog, unfortunately I don't have a ETA for this task.

**Comment by matthewadams** [comment]
not stale

**Comment by rafariossaa** [comment]
Hi,
This task is in our backlog, unfortunately I don't have a ETA for this task.

**Comment by rkettelerij** [comment]
Any ETA now?

**Comment by matthewadams** [comment]
Not stale 🤣

**Comment by rafariossaa** [comment]
Hi,
  Sorry, no ETA yet.
  We are a small team and we have to handle priorities, request, internal projects, etc.
  In any case, PR are welcome and we will be glad to review and merge them.
