### ISSUE TITLE
is broadcast_address supported?

### ISSUE THREAD

**Issue by yury-kozlov** [bitnami/bitnami-docker-cassandra#68]
I'm trying to set up multi-node Cassandra cluster with two data centers (on different regions, with 2 public IPs), but seems like bitnami docker image doesn't support `broadcast_address` input parameter. How can I configure multi-region support ?

According to [docs](https://docs.datastax.com/en/dse/6.7/dse-admin/datastax_enterprise/config/configSnitchEC2MultiRegion.html), `broadcast_address` parameter is required for cross-region communication:

> In the cassandra.yaml, set the listen_address to the private IP address of the node, and the **broadcast_address** to the public IP address of the node.
This allows DataStax Enterprise nodes in one EC2 region to bind to nodes in another region, thus enabling multiple datacenter support.

**Comment by andresbono** [comment]
Hi @yury-kozlov,

We don't have input parameters for every option, that would be impossible to maintain! For that reason, we only have available a subset of parameters.

However, you can always mount and customize your own configuration file. To do that, please check these sections of the readme:

[Configuration file](https://github.com/bitnami/bitnami-docker-cassandra#configuration-file)

**Comment by yury-kozlov** [comment]
thanks for prompt response, @andresbono!

I thought that multi-node cross-region distribution of data in Cassandra are the features that attract this database.
Do I understand right, that those features are not supported out of the box in bitnami docker image (without defining custom configuration file)? I'm asking because in [Cassandra "Official Image"](https://hub.docker.com/_/cassandra) I can easily achieve this.

**Comment by yury-kozlov** [comment]
@andresbono, following your advise, I mounted custom configuration file (as k8s config map) and deployed cassandra using bitnami chart.
I can see that my config has completely overwritten all input paramters defined in the helm chart. 
For example, all those variables I'm forced to initialize by myself:
```
	 commitlog_directory "${CASSANDRA_DATA_DIR}/commitlog"
	 hints_directory "${CASSANDRA_DATA_DIR}/hints"
	 cdc_raw_directory "${CASSANDRA_DATA_DIR}/cdc_raw"
	 saved_caches_directory "${CASSANDRA_DATA_DIR}/saved_caches"
	 "num_tokens" "$CASSANDRA_NUM_TOKENS" "no"
	 "cluster_name" "$CASSANDRA_CLUSTER_NAME"
	 "listen_address" "$host"
	 "seeds" "$CASSANDRA_SEEDS"
	 "start_rpc" "$CASSANDRA_ENABLE_RPC" "no"
	 "enable_user_defined_functions" "$CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS" "no"
	 "rpc_address" "$rpc_address"
	 "broadcast_rpc_address" "$host"
	 "endpoint_snitch" "$CASSANDRA_ENDPOINT_SNITCH"
	 "internode_encryption" "$CASSANDRA_INTERNODE_ENCRYPTION"
	 "keystore" "$CASSANDRA_KEYSTORE_LOCATION"
	 "keystore_password" "$CASSANDRA_KEYSTORE_PASSWORD"
	 "truststore" "$CASSANDRA_TRUSTSTORE_LOCATION"
	 "truststore_password" "$CASSANDRA_TRUSTSTORE_PASSWORD"
	 "native_transport_port" "$CASSANDRA_CQL_PORT_NUMBER" "no"
	 "storage_port" "$CASSANDRA_TRANSPORT_PORT_NUMBER" "no"
	 "authenticator" "PasswordAuthenticator"
	 "authorizer" "CassandraAuthorizer"
```

I don't think this is the best solution to write my own configuration if I already use helm chart for this. It would be more practical to a) expose cluster variables on the level of docker image and helm chart. OR b) provide an option to override only those variables that were specified in custom config  leaving the default ones as is.

**Comment by andresbono** [comment]
Hi again @yury-kozlov, in that case, I think it's fine to add a variable like `CASSANDRA_BROADCAST_ADDRESS`. Would you like to open a PR with the changes that you see necessary?

You can find all the logic here:

https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh

Let us know what you think!

**Comment by yury-kozlov** [comment]
I tried to test my changes locally, but can't build the image. Moreover, even without any changes, when I run `docker build -t bitnami/cassandra:latest ./3/debian-10/ ` inside the cloned repository I get this error:

> Step 6/20 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "2.7.17-3" --checksum a6269e56bb709da6d7c7145bd685b5ecc3056b5a38792c9dc3165785c41296e9
 ---> Running in d615ece604aa
: not found /opt/bitnami/scripts/libcomponent.sh:
: not found /opt/bitnami/scripts/libcomponent.sh:
: not found: /opt/bitnami/scripts/libcomponent.sh:
/bin/sh: 24: /opt/bitnami/scripts/libcomponent.sh: 1: name is required
The command '/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "2.7.17-3" --checksum a6269e56bb709da6d7c7145bd685b5ecc3056b5a38792c9dc3165785c41296e9' returned a non-zero code: 2

However, if I run docker build with github context, everything is fine: `docker build -t bitnami/cassandra:latest 'https://github.com/bitnami/bitnami-docker-cassandra.git#master:3/debian-10'`

What am I missing?
My linux is Ubuntu 18.04.4 LTS (Bionic Beaver)". I am a root user. Linux is hosted on virtualbox if this matters. Docker 19.03.8.

**Comment by andresbono** [comment]
Thanks, @yury-kozlov, let us know if you face any other issues.

**Comment by yury-kozlov** [comment]
created a pull request https://github.com/bitnami/bitnami-docker-cassandra/pull/71

**Comment by andresbono** [comment]
Great, @yury-kozlov!! Thank you very much.
