### ISSUE TITLE
Cassandra 3.11.6 cannot start with replica=3

### ISSUE THREAD

**Issue by majjihari** [bitnami/bitnami-docker-cassandra#70]
**Description**

Unable to resolve other hosts when replica=3.

I am using onpremises cluster deployed with kubespray

**Steps to reproduce the issue:**

1. helm install cassandra bitnami/cassandra -n cassandra -f values-production.yaml

**Describe the results you received:**

Hostname cassandra-0.cassandra-headless.cassandra.svc.cluster.local could not be resolved. This could lead to connection issues

**Describe the results you expected:**

The cluster should be up without any problem resolving the FQDN of pods from one another.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

```
kubernetes version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

hem version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by Mauraza** [comment]
Hi @majjihari,
 
I don't be able to reproduce the issue, have you used the same values of [values-production.yaml](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values-production.yaml)?
