### ISSUE TITLE
198 killed

### ISSUE THREAD

**Issue by gutorc92** [bitnami/bitnami-docker-cassandra#73]
I am trying to use the bitnami cassandra helm chart and getting this error:

![image](https://user-images.githubusercontent.com/2671806/81075969-70c4cf00-8ec1-11ea-9e2c-f702bb1d8b42.png)

i use my own values file:
```
image:
    registry: atf.intranet.bb.com.br:5001
    repository: bitnami/cassandra
    debug: true
keyspace: cortex
timeout: 1000ms
replicationFactor: 1
username: cassandra
hostVerification: false
ssl: false
consistency: LOCAL_QUORUM
nodeSelector: 
    feature.node.k8s.bb/nas: "true"
cluster:
    jvm:
        maxHeapSize: "3Gi"
persistence:
    storageClass: nas-client
resources:
    requests:
        cpu: 2
        memory: "4000Mi"
    limits:
        cpu: 4
        memory: "6000Mi"
``

**Comment by rafariossaa** [comment]
Hi,
  Could you paste the full log ? I would like to see if it is reusing a previous mounted volume.
  In any case, could you try deleting the helm and the PVCs ?

**Comment by gutorc92** [comment]
@rafariossaa, I have deleted all pvc and try to reinstall the chart but I get the same error.

**Comment by gutorc92** [comment]
@rafariossaa, if a use 6000Mi on request memory the error change to:
![image](https://user-images.githubusercontent.com/2671806/81311092-56bef400-905b-11ea-8ed2-fc01a940447d.png)

**Comment by gutorc92** [comment]
@rafariossaa thanks for your help, I can solve the problem. Cassandra needs minimum 8gb of memory to start. I have to ask the admin of my cluster to update the memory restrictions.

**Comment by rafariossaa** [comment]
Hi @gutorc92,
  I am happy you were able to solve the issue. Thanks for sharing!.

Best regards,

**Comment by kumarganesh2814** [comment]
I also Faced same issues, Had to remove Limitrange and Quota from ns which used to deploy kong.

**Comment by rafariossaa** [comment]
Hi @kumarganesh2814 ,
  Thanks for sharing !

**Comment by rafariossaa** [comment]
I am closing this issue.
