### ISSUE TITLE
High CPU utilization even when the cluster is idle

### ISSUE THREAD

**Issue by yogeshbidari** [bitnami/bitnami-docker-cassandra#74]
**Description**

We have 3 node cassandra cluster on kubernetes.
The CPU utilization of the cluster/pods is high even when there is no load or queries running on the cluster. We are using bitnami/cassandra:3.11.3 docker image. 
We are using grafana for monitoring the load.

**Steps to reproduce the issue:**

1. Install the 3 node cassandra cluster on gke
2. Grafana for monitoring

**Describe the results you received:**

When lot of queries were running sometimes the nodes CPU utilization goes over 100%, that is fine. But when there is no load or no queries were running the CPU utilization still remains high.

**Describe the results you expected:**

CPU utilization should be low when there is no load on the cluster

**Version**

- cassandra version: 3.11.3
- GKE version 1.14.10

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using GCP GKE for the k8s cluster deployment.

Assigned resource request and limits
Requests:
     - cpu: 3
     - memory: 15GB
Limits:
     - cpu: 6
     - memory: 30GB

**Comment by dani8art** [comment]
Hi @yogeshbidari, thank you for the feedback, I'm going to troubleshoot in a similar environment trying to figure out what is happening, it is going to take some time to prepare the environment and so on, I will come back to you with something soon.

**Comment by yogeshbidari** [comment]
Hi @dani8art ,

Any update on this issue?

**Comment by javsalgar** [comment]
Hi,

You said that you were using Grafana, it could be nice if you could share the graphs of the CPU usage. I wonder if the readiness/liveness probes could also be causing the CPU to increase. It is true that cassandra is a CPU/MEM consuming application so it could also be due to the JVM and any basic maintenance operations.

**Comment by javsalgar** [comment]
Do you have any other cassandra installation where you do not see this phenomenon?

**Comment by yogeshbidari** [comment]
The high utilization was because readiness/liveness probes, we were using nodetool status before.
Now we switched to TCP probe. It is reduced a bit, not completely. Even when the cluster is idle it is around 60% now.

**Comment by yogeshbidari** [comment]
I am not able to upload the screenshot of CPU utilisation.

**Comment by dani8art** [comment]
Hi @yogeshbidari, As @javsalgar said some time java applications need too many resources due to the JVM configuration and the environment where it is running, Could you try to go inside the Cassandra instances and execute the following to see the JVM heap usage?

```console
$ jmap -heap <pid>
```

**Comment by yogeshbidari** [comment]
I am getting version mis-match while running the jmap.
`Error attaching to process: sun.jvm.hotspot.runtime.VMVersionMismatchException: Supported versions are 25.252-b09. Target VM is 25.201-b09
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.runtime.VMVersionMismatchException: Supported versions are 25.252-b09. Target VM is 25.201-b09`

But I am able to get the heap form other command.
`root@cassandra-0:/# java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
     intx CompilerThreadStackSize                   = 0                                   {pd product}
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 1717567488                          {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 27460108288                         {product}
     intx ThreadStackSize                           = 1024                                {pd product}
     intx VMThreadStackSize                         = 1024                                {pd product}`

**Comment by dani8art** [comment]
That's good but what we would need is the Heap usage instead of the heap configurations. Sometimes `Garbage Collection` takes all the CPU or high part of it, GC can be improved by adjusting JVM HEAP SIZE parameters but first, we would need to check the current heap usage.

Please, could you try `jstat -gc [insert-pid-here]`?

**Comment by yogeshbidari** [comment]
Hi @dani8art ,

`jstat -gc` command is not working, it is giving error like `<pid> not found`.
Is there any other way we can get those metrics?

**Comment by dani8art** [comment]
Hi @yogeshbidari yes that is true it is because cassandra by defaultl use: `-XX:+PerfDisableSharedMem` to disable JVM connections so you can't access them directly. Please, could you apply these `sed` and restart the containers.

```
sed -i "s/-XX:+PerfDisableSharedMem/#-XX:+PerfDisableSharedMem/g" /opt/bitnami/cassandra/conf/jvm.options
```

if the previous file doesn't exist, please do this:

```
sed -i "s/-XX:+PerfDisableSharedMem/#-XX:+PerfDisableSharedMem/g" /opt/bitnami/cassandra/conf.default/jvm.options
```

then restart the containers and execute: 

```
jstat -gcutil <pid>
```

**Comment by yogeshbidari** [comment]
Hi @dani8art ,

Thanks for the help.
Here is the command output:
S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT
28.87   0.00  82.29   0.19  97.00  95.57      2    0.107     2    0.068    0.176

I have executed the command on the similar cluster in which containers are running with root privileges.
Usually cassandra runs with UID 1001, that doesn't have any username.

**Comment by yogeshbidari** [comment]
Jstat -gc command output.
```
$ jstat -gc 86
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
163840.0 163840.0  0.0   37248.9 1310720.0 1050032.0 6750208.0   48364.1   43432.0 42228.0 5776.0 5537.6      3    0.233   2      0.068    0.302

```

**Comment by dani8art** [comment]
that's good, sorry but I would need to see the new generation stats could you also execute `jstat -gcnewcapacity <pid>`?

**Comment by yogeshbidari** [comment]
Np, sharing the `jstat -gcnewcapacity <pid>` command output.
```
  NGCMN      NGCMX       NGC      S0CMX     S0C     S1CMX     S1C       ECMX        EC      YGC   FGC
 1638400.0  1638400.0  1638400.0 163840.0 163840.0 163840.0 163840.0  1310720.0  1310720.0    32     2

````

**Comment by dani8art** [comment]
Regarding the `NGCMX | Maximum new generation capacity` is only 1.6gb and `E | Eden space utilization as a percentage of the space's current capacity` is like an 82.29 %  and this could be a problem because when the code creates a new object it will need to get memory from this part. If it’s almost full or insufficient, JVM needs to scan the memory area to release memory. Before it’s done, the program can do nothing but wait.

ref: https://alexzeng.wordpress.com/2013/05/25/debug-cassandrar-jvm-thread-100-cpu-usage-issue/

Could we do a test setting these parameters in `cassandra-env.sh`

```bash
MAX_HEAP_SIZE="16G"
HEAP_NEWSIZE="4G"
```

**Comment by yogeshbidari** [comment]
I have changed the `MAX_HEAP_SIZE` and `HEAP_NEWSIZE` parameters in `cassandra-env.sh`.

Below are the command outputs:
```
jstat -gcutil 
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT
 15.62   0.00  44.04   0.10  97.04  94.73      2    0.216     2    0.074    0.290

jstat gc
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
419392.0 419392.0 65502.8  0.0   3355520.0 1477755.7 12582912.0  12877.2   43252.0 41971.7 5828.0 5520.8      2    0.216   2      0.074    0.290

jstat -gcnewcapacity 
  NGCMN      NGCMX       NGC      S0CMX     S0C     S1CMX     S1C       ECMX        EC      YGC   FGC
 4194304.0  4194304.0  4194304.0 419392.0 419392.0 419392.0 419392.0  3355520.0  3355520.0     2     2
```

**Comment by dani8art** [comment]
Ok, it seems to be a bit less overhead right? do you have CPU usage statistics since you did the changes?

**Comment by yogeshbidari** [comment]
Hi @dani8art ,

I was testing on some test cluster, there, the utilization is bit less.
I have to apply these changes in actual environment, just wanted to know changing these won't cause any other problem in the cluster right?

**Comment by dani8art** [comment]
Nice to see that it could work, it shouldn't cause more problems since we are just adding more resources to the GC. Please, you keep us updated. Thank you!
