### ISSUE TITLE
cannot create directory '/bitnami/cassandra': Permission denied

### ISSUE THREAD

**Issue by thg303** [bitnami/bitnami-docker-cassandra#76]
docker-compose.yml file is corrupted.

**Steps to reproduce the issue:**

1. `curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-cassandra/master/docker-compose.yml > docker-compose.yml`
2. `mkdir cassandra_data`
3. edit docker-compose.yml to use the local dir:`    volumes:
      - './cassandra_data:/bitnami'`
4. docker-compose up -d
5. docker logs cassandra_cassandra_1

**Describe the results you received:**
docker logs cassandra_cassandra_1 
cassandra 13:03:56.03 
cassandra 13:03:56.03 Welcome to the Bitnami cassandra container
cassandra 13:03:56.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra 13:03:56.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra 13:03:56.03 
cassandra 13:03:56.03 INFO  ==> ** Starting Cassandra setup **
cassandra 13:03:56.04 INFO  ==> Validating settings in CASSANDRA_* env vars..
cassandra 13:03:56.04 WARN  ==> You set the environment variable CASSANDRA_PASSWORD=cassandra. This is the default value when bootstrapping Cassandra and should not be used in production environments.
cassandra 13:03:56.06 INFO  ==> Initializing Cassandra database...
mkdir: cannot create directory '/bitnami/cassandra': Permission denied

**Describe the results you expected:**

image runs properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 69
  Running: 62
  Paused: 0
  Stopped: 7
 Images: 383
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.7GiB
 Name: iranserver
 ID: BKG4:EBOQ:ONSE:TDBV:5QLM:KDP6:Z76U:DLXQ:KBUO:3MQE:SK2C:JPAL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by bcashier** [comment]
Put the full path to:
'./cassandra_data:/bitnami'`

Example (not necessary but help):
'/var/logs/cassandra_data:/bitnami'`

And you have to chmod the folder:
`chmod +x /var/logs/cassandra_data`

**Comment by thg303** [comment]
thank you @bcashier for the hint. `chmod 777 /var/logs/cassandra_data` solved the issue.

**Comment by juancki** [comment]
Bitnami images use the user 1001
```
volumes:
  - ./cassandra_data:/bitnami
```
```
sudo chown -R 1001:1001 <directory>
```
https://techoverflow.net/2018/12/15/solving-bitnami-docker-redmine-cannot-create-directory-bitnami-mariadb-permission-denied/

**Comment by miguelaeh** [comment]
HI @thg303 ,
You should not use `777` perimssions, that is a potential risk for your deployment. Please consider the following:
```
chown -R 1001 ./cassandra_data
```
Do not change the group since it should be root.
