### ISSUE TITLE
[FEATURE] Removing Default cassandra super user

### ISSUE THREAD

**Issue by maegul** [bitnami/bitnami-docker-cassandra#81]
The current setup (as far as I understand it) doesn't allow for the removal of the default cassandra user, even when a new super/admin user is being added through docker environment variables. 

The pivotal code appears to be [here](https://github.com/bitnami/bitnami-docker-cassandra/blob/568da3e62e46997b8c9a532764fad9797db3c084/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L721).

Given that this is undesirable, it would be nice if the default user could be removed through an environment variable, or that this behaviour were documented clearly.

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @maegul thank you so much for the suggestion!

We think it would be nice to have this feature included in our Cassandra image. Would you like to contribute it with a PR? If you have a chance we will be happy to handle it.
