### ISSUE TITLE
Does Cassandra Supports Point-in-time Recovery(PITR)?

### ISSUE THREAD

**Issue by shanmukha511** [bitnami/bitnami-docker-cassandra#83]
**Description**

I want to implement cassandra Point in time recovery.i am not getting proper documentation for the same .
Is it possible to implement if so any document for same. moreover i see oly enterprise edition docs.

i have added configuration in commitlog_archiving.properties but restore to that point in time not working

configuration below

archive_command=/bin/ln /var/lib/cassandra/commitlog/ /u01/cassandra/arch/
restore_command=/bin/cp -f /u01/cassandra/arch/ /var/lib/cassandra/commitlog/
restore_directories=/u01/cassandra/arch/
restore_point_in_time=2020:12:18 04:48:00

wt is restore command and restore directories will do here if we simple copy the archive file that commit log replay will happen automatically?

If i copy all archive logs say i have 3 log files and i mention restore point in time and restart the node can i get data before that point? 

**Describe the results you received:**

PITR not working as expected?

**Describe the results you expected:**

PITR shld work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version** : 3.11.3

**Comment by rafariossaa** [comment]
Hi,
  Could you point me to documentation where that configuration is indicated ?. I can not find a example of that in the apache cassadra site. 
  Sometimes, this kind of features are not in the free/open version of the products.
  Also, I would suggest you to ask in apache cassandra forums, I am sure they can indicate you the configuration settings you need.

**Comment by shanmukha511** [comment]
Hi @rafariossaa 

Please find the below links of doc for configuration of PITR for cassandra.

https://cassandra.apache.org/doc/latest/configuration/cass_cl_archive_file.html
https://support.datastax.com/hc/en-us/articles/115001593706-Manual-Backup-and-Restore-with-Point-in-time-and-table-level-restore-

**Comment by rafariossaa** [comment]
Hi @shanmukha511 ,
  Thanks for sharing the documents.
   I am creating an internal task to look for a configuration procedure, however I can not provide an ETA for it.
  Did you have any luck asking in cassandra's forums ?.

**Comment by shanmukha511** [comment]
Hi @rafariossaa 

I raised ticket in Jira regarding the same. They asked me to use user mailing list
. 
I saw the Cassandra user mailing list about PITR there are some issues but they are pretty old not exactly solution they have mentioned in the Cassandra forum.

And one more quick question if we want to restore to a particular point in time using commit log. Do we need to remove the 
key space data which existed and then perform PITR process?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry I am not very sure on that neither. I guess as in other databases, you don't need to remove data, but once you recover on a point in the time, you only will have those data and not other ones.
  If it happens you get some answer from your ticket, please don't hesitate to share the information so other users with the same question can find an answer.
Thanks.

**Comment by shanmukha511** [comment]
Hi @rafariossaa ,
sure will share information if i get anything on this PITR.
Thanks.

**Comment by rafariossaa** [comment]
Thanks you.

**Comment by sunstonesecure-robert** [comment]
bump - any new guidance?

**Comment by rafariossaa** [comment]
I am sorry, no news in our side.
@shanmukha511 Have you had better luck ?.
