### ISSUE TITLE
Set listen_address for istio proxy

### ISSUE THREAD

**Issue by KuroObi** [bitnami/bitnami-docker-cassandra#88]
For Istio the listen_address needs to be set to 0.0.0.0 (https://istio.io/latest/faq/applications/#cassandra)
This is currently not possible to set this individual.

**Comment by andresbono** [comment]
Hi @KuroObi, thanks for opening this issue. What did you try so far? Are you using our Helm Chart for Cassandra? Did you try with the following environment variables?

- `CASSANDRA_HOST`
- `CASSANDRA_BROADCAST_ADDRESS`

**Comment by KuroObi** [comment]
Following the istio instructions I set the following:
- CASSANDRA_HOST = 0.0.0.0
- CASSANDRA_BROADCAST_ADDRESS = status.podIP

This leads to the follwing error message: 

> Exception encountered during startup: listen_address cannot be a wildcard address (0.0.0.0)!

The Casssandra documentation states that the listen_address should never be set to 0.0.0.0 (https://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html?highlight=listen_address#listen-address)
(https://issues.apache.org/jira/browse/CASSANDRA-256)

Settinging:
- CASSANDRA_HOST = 127.0.0.1
- CASSANDRA_BROADCAST_ADDRESS = status.podIP
enables a correct startup and communication with the cassandra cluster.

But this leads to this:
![image](https://user-images.githubusercontent.com/2558064/109295676-6e0bdf80-782f-11eb-928f-3eb132415dd2.png)

**Comment by andresbono** [comment]
Thanks for the clarification, @KuroObi. It seems there is an incompatibility between the Cassandra settings and the Istio requirements. The official documentation for both components is being contradictory, so I'm not sure if it is actually supported.

Do you have any suggestions to do at container or chart level to resolve the situation?

**Comment by KuroObi** [comment]
I don't think there is anythign to do on thje container level at this moment.

**Comment by andresbono** [comment]
Thanks @KuroObi. We will leave this issue open for some time in case someone has any suggestions to resolve it.
