### ISSUE TITLE
[bitnami/cassandra] Increase vm.max_map_count to1048575

### ISSUE THREAD

**Issue by jemantheiy** [bitnami/bitnami-docker-cassandra#90]
**Description**

Production cassandra nodes are stating the max_map_count is too low, I'm getting a map failed on some nodes.  Need to increase the vm.max_map_count as recommended by https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/config/configRecommendedSettings.html

Need to set this on the container since I'm in K8s and docker image dies prior to startup.  

**Describe the results you received:**

If the JVM error message is java.lang.OutOfMemoryError: Map failed, we can try the following:
Check the output of sysctl -a and ensure the value of vm.max_map_count is set to 1048575 as detailed in our recommended production settings document.

**Describe the results you expected:**
Warning goes way on new pods, and map failure goes away on trouble nodes.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

any of the 3.11 cassandra docker images.  

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @jemantheiy,

You are right, that job is a hook, it's because of `helm` you can check this issue  https://github.com/helm/helm/issues/4434. 
We are working to eliminate these hooks, but we don't know when they will be available.

**Comment by Mauraza** [comment]
Hi @jemantheiy,

Could you add the output of the command ` sysctl -a | grep vm.max_map_count`?

**Comment by jemantheiy** [comment]
65530

**Comment by Mauraza** [comment]
Hi @jemantheiy,

to change the `vm.max_map_count` you need to run the following command
```
sudo sysctl -w vm.max_map_count=1048575
```
you can check it with the command shared above:
```
sudo sysctl -a | grep vm.max_map_count
```
