### ISSUE TITLE
Where do the tarballs come from?

### ISSUE THREAD

**Issue by a-nldisr** [bitnami/bitnami-docker-cassandra#91]
**Description**
Hi, question: 
Today I have been going through the Cassandra setup, we have an old Cassandra version running (which cannot be upgraded) and we plan to connect this old version of Cassandra to a new datacenter running in Kubernetes. Cassandra does not allow version mismatch in the version we run in, so we need to build a container supporting Cassandra 3.0.10. To achieve this I was planning to build a container with this Cassandra version. This cluster afterwards needs to be upgraded to later versions, this project seemed like an interesting candidate to build upon further.

Today I have been inspecting the Cassandra tgz and found that it contains bitnami specific objects (JSON files, like bitnami.json). I would like to know where this tgz originates from, I couldn't find it in the code base (the JSON file contains a few strings that cannot be found anywhere in the codebase.)

**Comment by carrodher** [comment]
Since a specific version (3.11.4) the Cassandra logic was migrated from nami to bash, see https://github.com/bitnami/bitnami-docker-cassandra#3114-debian-9-r188-and-3114-ol-7-r201. The nami logic was based on an internal (and private) tool. From this moment we moved everything to public bash logic, but the old versions are still using the nami one

**Comment by a-nldisr** [comment]
So if I understand it correct:
You use the libcassandra.sh scripts to build the tarballs, then upload them to the fileserver. Download them with the libcomponent.sh script and install them?

**Comment by chistyakov** [comment]
Hi!

We have the exactly the same issue, only old Cassandra version is 3.6

* How can I list available tarballs on `https://downloads.bitnami.com/files/stacksmith/cassandra-*` ?
* What is the right way to build tarball with specific Cassandra version yourself ?

**Comment by a-nldisr** [comment]
> * What is the right way to build tarball with specific Cassandra version yourself ?

You can retrieve the cassandra tarballs with parts of the script libcomponent.sh, i filtered out the parts needed to get the tar:

```
#!/bin/bash

func() {
    local OS_ARCH="amd64"
    local OS_FLAVOUR="debian-10"
    local OS_NAME="linux"
    local DOWNLOAD_URL="https://downloads.bitnami.com/files/stacksmith"

    local name="cassandra"
    local version="3.11.10-0"
    local base_name="${name}-${version}-${OS_NAME}-${OS_ARCH}-${OS_FLAVOUR}"


    echo "${DOWNLOAD_URL}/${base_name}.tar.gz"
    curl "${DOWNLOAD_URL}/${base_name}.tar.gz"
}

func
```

I tried to retrieve older versions of Cassandra and ran into that they are not built and available for download. 

Besides not having access to older versions, a large part of the selection of tools to run for the business we support is that these tools offer insight into the code so we can make changes like these. Without the option to see how these tars are built in general I have to advise not to use a project since the core is closed source. I however suspect that this was forgotten. Since it would seem silly to me to opensource the helm chart, the docker containers but not the files used in the docker containers. 

Back to the solution: Yesterday I have downloaded the latest version, replaced the files/cassandra folder with the older version I require (which seems to be just the extracted tarball from https://cassandra.apache.org/download/ and adjusted the version of cassandra in the bitnami.json. I will upload this to an S3 bucket and in the fork I made I will point to my personal S3 bucket. From there I will see what will happen, perhaps I have to make adjustments to get the container startup cassandra or make version-specific changes.

**Comment by carrodher** [comment]
Those tarballs are generated by a tool called [Blacksmith](https://github.com/bitnami/blacksmith), which basically uses the upstream source code or binaries and compiles them when needed, then the tarball is uploaded to a public s3 bucket. In that process, everything except the compilation recipe (when it is needed to compile) is publicly available (see the blacksmith project in GH for more info).

 Once the tarball is generated it is needed to configure and initialize the application. In old versions, this was done by another tool called [nami](https://github.com/bitnami/nami), although the files were present in the image they were not available in GitHub. Since a specific version (`3.11.4`) this logic was migrated from nami to bash, see https://github.com/bitnami/bitnami-docker-cassandra#3114-debian-9-r188-and-3114-ol-7-r201 so everything is publicly available in this repository.

You can obtain the old tarball from the s3 bucket but you will also need to take a look at the nami configuration/initialization logic since the mentioned old image is still using this approach.

Not sure if it is related but Bitnami/VMware provides the [Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog) where the different containers and Helm Charts can be built based on different distros, pushed to custom registries and all the licenses, components, antivirus scanner, etc are reported.

**Comment by a-nldisr** [comment]
Thanks for the update! :) Would you be okay with me making a PR about how to use Blacksmith as an entry to the readme?

**Comment by carrodher** [comment]
Yes sure, any PR is more than welcome; we will be happy to review it.
In this case, are you referring to the[ Cassandra container README](https://github.com/bitnami/bitnami-docker-cassandra/blob/master/README.md) or the [Blacksmith one](https://github.com/bitnami/blacksmith/blob/master/README.md)? (just in case it apply to all the containers and not only to Cassandra)

**Comment by chistyakov** [comment]
I managed to up Cassandra 3.6 with such Dockerfile:

```
FROM docker.io/bitnami/minideb:buster
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux"

# ========= <patched>
ENV CASSANDRA_VERSION=3.6
ENV CASSANDRA_SHA1=00ded1955444626add2367b5871153dd604eeae0
# ========= </patched>

COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages acl ca-certificates curl gzip libbz2-1.0 libc6 libgcc1 libjemalloc2 libncursesw6 libreadline7 libsqlite3-0 libssl1.1 libtinfo6 procps tar zlib1g
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "2.7.18-12" --checksum 628dbe1685e75f1db52983a894598a9384134b510501a09267fbb14ff070ff68
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "1.8.282-0" --checksum 473d0ab64adfe82d84dd810c28e0f22242eeffbaf74a85febf7586ce013aa7ba
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "yq" "3.4.1-0" --checksum c88c76a7b5214407821771e5fc340f0320d5ded19eada938629603a982b8b640
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.12.0-2" --checksum 4d858ac600c38af8de454c27b7f65c0074ec3069880cb16d259a6e40a46bbc50

# ========= <patched>
#RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "cassandra" "3.11.10-0" --checksum 10d89e5093b52383e456a7aad054bbc636d5b4a715152b75da1d610256399600

RUN curl --remote-name --silent "https://archive.apache.org/dist/cassandra/${CASSANDRA_VERSION}/apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz" && \
 echo "${CASSANDRA_SHA1} ./apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz" | sha1sum --check && \
 mkdir /opt/bitnami/cassandra && \
 tar --directory /opt/bitnami/cassandra --extract --gunzip --file "apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz" --no-same-owner --strip-components=1 "apache-cassandra-${CASSANDRA_VERSION}" && \
 mv /opt/bitnami/cassandra/conf /opt/bitnami/cassandra/conf.default && \
 rm apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz
# ========= </patched>

RUN chmod g+rwX /opt/bitnami
RUN ln -s /opt/bitnami/scripts/cassandra/entrypoint.sh /entrypoint.sh
RUN ln -s /opt/bitnami/scripts/cassandra/run.sh /run.sh

COPY rootfs /
RUN /opt/bitnami/scripts/cassandra/postunpack.sh
ENV BITNAMI_APP_NAME="cassandra" \
    BITNAMI_IMAGE_VERSION="${CASSANDRA_VERSION}-welltory-debian-10-r51" \
    PATH="/opt/bitnami/python/bin:/opt/bitnami/java/bin:/opt/bitnami/common/bin:/opt/bitnami/cassandra/bin:$PATH"

# ========= <patched>
ENV CQLSH_NO_BUNDLED=true
COPY cqlsh-requirements.txt .
RUN pip install -r cqlsh-requirements.txt
# ========= </patched>

EXPOSE 7000 9042

USER 1001
ENTRYPOINT [ "/opt/bitnami/scripts/cassandra/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/cassandra/run.sh" ]
```
and cqlsh-requirements.txt
```
cassandra-driver==3.15.1
futures==3.3.0
six==1.15.0
```

**Comment by carrodher** [comment]
Thanks for letting us know, I hope it is useful for other users!
