### ISSUE TITLE
Cassandra backup which is taken in 3.11.3 and trying to restore in 3.11.10 is Not working as expected

### ISSUE THREAD

**Issue by shanmukha511** [bitnami/bitnami-docker-cassandra#92]
**Description**

Have took backup of data of Cassandra 3.11.3 version and upgraded Cassandra to 3.11.10 and tried to restore the data getting failed with below error for each keyspace.

Parameters:
K8s namespace: default
Statefulset name: Cassandra
Current expected number of replicas is 3

```
Waiting for equal desired and current number of replicas
Statefulset has equal current and desired number of replicas
Checking if required files exists
All required files are available

Detecting number or archives...
Found backup-0.tar.gz
Found backup-1.tar.gz
Found backup-2.tar.gz
Preparing to restore a backup of keyspace 'javapoint' from 3 archieves
Performing restore of 3 sized cluster
Restoring schema
**<stdin>:3:Invalid syntax at char 37
<stdin>:3:  Warning: Cannot create directory at `/.cassandra`. Command history will not be saved.
<stdin>:3:                                      ^**

Warnings :
dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0

dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0


Warnings :
dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0

dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0
```
**command terminated with exit code 2**

**Steps to reproduce the issue:**

1. Take backup of 3.11.3 Cassandra data
2. Restore data in 3.11.10 Cassandra using restore mechanism
3. Restore of each keyspace will be failed with syntax error and get terminated with exited code2.

**Describe the results you received:**

1. Tables and keyspaces getting restored but data is not getting restored.

**Describe the results you expected:**

1. Keyspace , Tables and data should get restored.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
GKE

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,
Are there any other logs in the container? I don't see any error on the above one.

Also, the `/.cassandra` directory should exists by default:
```
docker run --rm -it bitnami/cassandra bash
I have no name!@e5444b5ec084:/$ ls -la
total 84
drwxr-xr-x   1 root root 4096 May  6 07:05 .
drwxr-xr-x   1 root root 4096 May  6 07:05 ..
drwxrwxr-x   2 root root 4096 May  5 04:35 .cassandra
-rwxr-xr-x   1 root root    0 May  6 07:05 .dockerenv
drwxr-xr-x   1 root root 4096 May  5 04:35 bin
drwxr-xr-x   3 root root 4096 May  5 04:35 bitnami
drwxr-xr-x   2 root root 4096 Feb 18 11:59 boot
drwxr-xr-x   5 root root  360 May  6 07:05 dev
drwxrwxr-x   2 root root 4096 May  5 04:35 docker-entrypoint-initdb.d
lrwxrwxrwx   1 root root   44 May  5 04:35 entrypoint.sh -> /opt/bitnami/scripts/cassandra/entrypoint.sh
drwxr-xr-x   1 root root 4096 May  6 07:05 etc
drwxr-xr-x   2 root root 4096 Feb 18 11:59 home
drwxr-xr-x   1 root root 4096 Sep 25  2017 lib
drwxr-xr-x   2 root root 4096 Feb 18 11:59 lib64
drwxr-xr-x   2 root root 4096 Feb 18 11:59 media
drwxr-xr-x   2 root root 4096 Feb 18 11:59 mnt
drwxrwxr-x   1 root root 4096 May  5 04:34 opt
dr-xr-xr-x 791 root root    0 May  6 07:05 proc
drwx------   2 root root 4096 Feb 18 11:59 root
drwxr-xr-x   4 root root 4096 Feb 18 11:59 run
lrwxrwxrwx   1 root root   37 May  5 04:35 run.sh -> /opt/bitnami/scripts/cassandra/run.sh
drwxr-xr-x   1 root root 4096 May  5 04:35 sbin
drwxr-xr-x   2 root root 4096 Feb 18 11:59 srv
dr-xr-xr-x  13 root root    0 Dec 15 07:35 sys
drwxrwxrwt   1 root root 4096 May  6 07:05 tmp
drwxrwxr-x   1 root root 4096 May  5 04:34 usr
drwxr-xr-x   1 root root 4096 Feb 18 11:59 var
```

**Comment by shanmukha511** [comment]
Hi @miguelaeh
Yes it is there (.cassandra folder) in 3.11.10 but that folder not present in 3.11.3 is it expected behaviour? Because of this .cassandra folder not present in 3.11.3 when we are taking backup of keyspaces we are getting that warning message added to schema.cql for each keyspace.
when we restore the keyspaces in 3.11.3 it encounters that warning message  but still proceed to restore the data.
but wn we restore in 3.11.10 as soon as it encounters the warning message it just exits with error code 2.
Is this expected behaviour?

You can see warning message in schema sql file.

**Example backup schema file:**


Warning: Cannot create directory at `/.cassandra`. Command history will not be saved.


CREATE KEYSPACE abc WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE abc.t2 (
    id int PRIMARY KEY,
    k int,
    v text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,
I am not sure why it didn't exist on version 3.11.3. Could you try creating it empty and see what happens? That folder should not contain any sensitive data, maybe creating it empty will bypass the error code 2.
If it is a production workload I would suggest that you test it first in a different environment.

**Comment by shanmukha511** [comment]
Hi @miguelaeh,
Yes we can create empty .Cassandra directory and check whether below warning occurring or not 
**Cannot create directory at /.Cassandra. Command history will not be saved.**.
 But actually thing which i want to know let say in 3.11.3 whenever cqlsh gets syntax error does it exits or proceed?
 In 3.11.3 i see if cqlsh if it gets error also it proceeds.
 
 You can take above schema file with warning mentioned and pass schema file as input to cqlsh for both 3.11.3 and 3.11.10  .find below command

 **command:**
 kubectl exec -i cassandra-0 -n default -- cqlsh -u cassandra -p '****' < backup-schema2.cql
 
 If you execute above command with above schema file in both 3.11.3 and 3.11.10 you can get difference
 
And in 3.11.10 if  the cqlsh gets any syntax error or any error why its exiting with status code 2?
Does changes made to cqlsh above 3.11.3 can we find in release notes in that case?

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,
I tested your example backup file in both cases without any issues. I used our Helm Chart to deploy Cassandra in both versions:
```console
> helm install cassandra bitnami/cassandra
> kubectl exec -i cassandra-0  -- cqlsh -u cassandra -p '1nVXoE4JaU' < /tmp/cql.sh

Warnings :
dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0

dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0
```

And with the old version:
```console
> helm install casssandra-2 bitnami/cassandra --version 2.1.2
>  kubectl exec -i casssandra-2-cassandra-0  -- cqlsh -u cassandra -p 'IcS0z51HEN' < /tmp/cql.sh

Warning: Cannot create directory at `/.cassandra`. Command history will not be saved.


Warnings :
dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0

dclocal_read_repair_chance table option has been deprecated and will be removed in version 4.0
```

As you can see it is the same output.

We also have a guide to backup and restore Cassandra at https://docs.bitnami.com/google-templates/infrastructure/cassandra/administration/backup-restore/. Maybe it can help you.

**Comment by shanmukha511** [comment]
Hi @miguelaeh,
 wt does this file contains **/tmp/cql.sh**?

**Comment by miguelaeh** [comment]
>wt does this file contains /tmp/cql.sh?

It contains the file you shared above at https://github.com/bitnami/bitnami-docker-cassandra/issues/92#issuecomment-833331673


>Note: Pls include warning message as it is in schema.cql and give try

Why should you include a warning message in a cql file? Try removing it, that can be the source of the syntax error. I did it without the warning and it worked. Are you generating te backup as explained [here](https://docs.bitnami.com/google-templates/infrastructure/cassandra/administration/backup-restore/)?

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,

> Does any changes were made in respective to cqlsh after 3.11.3 like whenever cqlsh encounter syntax error or any kind of other error jst exit the script with error code 2 like that?

We don't have control of the `cqlsh` script. We package the image using the upstream source code so that's probably a question to ask to the Cassandra team.

> Do we have any document or release notes on the same which states that?

In the same way, I think you are looking for the release notes of Cassandra not the release notes of the container.

This repository packages Cassandra to create the container but we are not responsible of the source code of Cassandra, so if they changed the cqlsh script you should check the release notes in their repository.

Anyways, I think a warning message should never go inside the cql file so it is highly probable that the syntax check was changed between both versions by the Cassandra team.

**Comment by shanmukha511** [comment]
thanks @miguelaeh for the info

Let me check with cassandra team.

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,
I need more information, which errors are you receiving?

**Comment by shanmukha511** [comment]
Below error i am getting wn trying to restore in 3.11.10 for system_auth keyspace

<stdin>:3:AlreadyExists: Keyspace 'system_auth' already exists
<stdin>:23:Unauthorized: Error from server: code=2100 [Unauthorized] message="Cannot CREATE <keyspace system_auth>"
<stdin>:44:Unauthorized: Error from server: code=2100 [Unauthorized] message="Cannot CREATE <keyspace system_auth>"
<stdin>:64:Unauthorized: Error from server: code=2100 [Unauthorized] message="Cannot CREATE <keyspace system_auth>"
<stdin>:85:Unauthorized: Error from server: code=2100 [Unauthorized] message="Cannot CREATE <keyspace system_auth>"
command terminated with exit code 2

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,
Could you share what are you executing to do that?
I am not a Cassandra expert but checking the logs it seems that since the `system_auth` keyspace already exists you need to use the same credentials that were being used in order to connect to the database.

**Comment by shanmukha511** [comment]
Hi @miguelaeh,

I am just restoring the keyspace.
Yes the system keyspace exists by default wn u run cassandra and y am i trying to restoring the system_auth keyspace is we have use details ther in order to get users to be restored i am using that.
And credentials i am using to connect database are good if it was issue i would not able to connect.

This script i am calling to restore that keyspace with required backups
https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/cassandra/scripts/restore.sh

**Comment by miguelaeh** [comment]
Hi @shanmukha511 ,
Could you please share the full log of the script execution?
