### ISSUE TITLE
Override custom Cassandra config via environment variables

### ISSUE THREAD

**Issue by ankitjain28may** [bitnami/bitnami-docker-cassandra#94]
**Description**

I am passing my custom config via cassandra.yaml as a volume mount but I only want to change few configs like enabling `slow_query_log_timeout_in_ms: 5` and the remaining configuration should be taken from the environment variables. 
In general, the environment variables always have the highest priority but in this case, it doesn't work that way, it uses the custom config.

**Steps to reproduce the issue:**

1. Create a cassandra.yaml file locally with default config and set `slow_query_log_timeout_in_ms: 5`
2. Run a docker container 
```
docker run --name cassandra -v /local-path/cassandra.yaml:/bitnami/cassandra/conf/cassandra.yaml:ro --env CASSANDRA_CLUSTER_NAME=cassandra --env CASSANDRA_MOUNTED_CONF_DIR=/bitnami/cassandra/conf bitnami/cassandra:latest
```

**Describe the results you received:**

Now, if we exec in the container and check the `/opt/bitnami/cassandra/conf/cassandra.yaml` file contents, we can see the following output:
```
docker exec cassandra cat /opt/bitnami/cassandra/conf/cassandra.yaml | grep -i slow_query_log_timeout_in_ms 
# slow_query_log_timeout_in_ms: 5
docker exec cassandra cat /opt/bitnami/cassandra/conf/cassandra.yaml | grep -i cluster_name 
# cluster_name: 'Test Cluster'
```

**Describe the results you expected:**

In the above output, the name of the cluster should be picked from the environment variable i.e CASSANDRA_CLUSTER_NAME and set to `cassandra`. The same issue is happening while running the Cassandra cluster in Kubernetes since the `listen_address` is set to the node-IP via environment variables hostname but defining the custom configuration isn't overriding the `listen_address` causing the cluster unhealthy.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: 7MU6:BJMX:XKKC:YQMM:N2DA:6DR2:T6GJ:73E6:RNZL:6X6X:R3BX:QYRB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 125
  Goroutines: 109
  System Time: 2021-08-09T12:44:31.0930872Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by migruiz4** [comment]
Hi @ankitjain28may,

I'm sorry but environment variables being ignored when a configuration file is mounted externally is expected behavior:
https://github.com/bitnami/bitnami-docker-cassandra/blob/2c10262d2bd13ffee001d2b7f8999a2e6b1b7ae8/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L495-L500

If you'd like to tune some specific setting, you could use an init script to do so. For example:

```bash
#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

# Load libraries
. /opt/bitnami/scripts/libbitnami.sh
. /opt/bitnami/scripts/libcassandra.sh

# Load Cassandra environment variables
eval "$(cassandra_env)"

cassandra_yaml_set "slow_query_log_timeout_in_ms" 5
```

Then, run the Cassandra container using:
```
chmod u+x /local-path/my_script.sh
docker run --name cassandra -v /local-path/my_script.sh:/docker-entrypoint-initdb.d/my_script.sh:ro --env CASSANDRA_CLUSTER_NAME=cassandra bitnami/cassandra:latest
```

Expected output (after Cassandra initialized):
```
bitnami@dockerdev:~/projects/app-catalogue$ docker exec cassandra cat /opt/bitnami/cassandra/conf/cassandra.yaml | grep -i slow_query_log_timeout_in_ms slow_query_log_timeout_in_ms: '5'
bitnami@dockerdev:~/projects/app-catalogue$ docker exec cassandra cat /opt/bitnami/cassandra/conf/cassandra.yaml | grep -i cluster_name 
cluster_name: 'cassandra'
```

Alternatively, if you'd like to configure those settings using environment variables, feel free to send a PR with the necessary changes and we will be happy to review it and help with anything you need.

**Comment by ankitjain28may** [comment]
@migruiz4 Thanks for the response, will take a look and try this out.

**Comment by ankitjain28may** [comment]
@migruiz4 Hey, have tried running the above-provided solutions, it seems it's not working in my case.  When i tried running on local, I was getting some weird error during cassandra startup --
```
cassandra 07:02:33.01 INFO  ==> Initializing Cassandra database...
cassandra 07:02:33.42 INFO  ==> Deploying Cassandra from scratch
cassandra 07:02:33.43 INFO  ==> Starting Cassandra
cassandra 07:02:33.43 INFO  ==> Checking that it started up correctly
/opt/bitnami/scripts/libos.sh: line 269:   159 Killed                  "${cmd[@]}" "${args[@]}" > "$logger" 2>&1
cassandra 07:11:21.11 ERROR ==> Cassandra failed to start up
```
I tried to replicate the same solution in my k8s environment, but still the `slow_query_log_timeout_in_ms` is set to 500 which is the default value. Attaching the debug logs for the reference.
```
cassandra 09:39:05.28 INFO  ==> Deploying Cassandra with persisted data
cassandra 09:39:05.29 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
cassandra 09:39:05.29 INFO  ==> Starting Cassandra
cassandra 09:39:05.30 INFO  ==> Checking that it started up correctly
cassandra 09:39:05.31 DEBUG ==> Checking that log /opt/bitnami/cassandra/logs/cassandra_init_scripts_boot.log contains entry "Starting listening for CQL clients"
INFO  [main] 2021-08-17 09:42:26,885 Server.java:159 - Starting listening for CQL clients on /0.0.0.0:9042 (encrypted)...
cassandra 09:42:31.57 INFO  ==> Found CQL startup log line
cassandra 09:42:31.58 DEBUG ==> Checking status with nodetool
UN  10.22.101.132  1.98 GiB   256          56.0%             f05d0388-34a4-471a-9cf9-055c893949f0  rack1
cassandra 09:43:49.51 INFO  ==> Nodetool reported the successful startup of Cassandra
```
So, I got the log of loading scripts from initdb.d but didn't get the log of executing the file which is stated here - https://github.com/bitnami/bitnami-docker-cassandra/blob/a5e38cb4c253ada59f054d9009678a92b4333394/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L809

Is there any workaround or am I missing something here?

**Comment by ankitjain28may** [comment]
@migruiz4 Hey, have tried running the above-provided solutions, it seems it's not working in my case.  When i tried running on local, I was getting some weird error during Cassandra startup --
```
cassandra 07:02:33.01 INFO  ==> Initializing Cassandra database...
cassandra 07:02:33.42 INFO  ==> Deploying Cassandra from scratch
cassandra 07:02:33.43 INFO  ==> Starting Cassandra
cassandra 07:02:33.43 INFO  ==> Checking that it started up correctly
/opt/bitnami/scripts/libos.sh: line 269:   159 Killed                  "${cmd[@]}" "${args[@]}" > "$logger" 2>&1
cassandra 07:11:21.11 ERROR ==> Cassandra failed to start up
```
I tried to replicate the same solution in my k8s environment, but still, the `slow_query_log_timeout_in_ms` is set to `500` which is the default value. Attaching the debug logs for reference.
```
cassandra 09:39:05.28 INFO  ==> Deploying Cassandra with persisted data
cassandra 09:39:05.29 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
cassandra 09:39:05.29 INFO  ==> Starting Cassandra
cassandra 09:39:05.30 INFO  ==> Checking that it started up correctly
cassandra 09:39:05.31 DEBUG ==> Checking that log /opt/bitnami/cassandra/logs/cassandra_init_scripts_boot.log contains entry "Starting listening for CQL clients"
INFO  [main] 2021-08-17 09:42:26,885 Server.java:159 - Starting listening for CQL clients on /0.0.0.0:9042 (encrypted)...
cassandra 09:42:31.57 INFO  ==> Found CQL startup log line
cassandra 09:42:31.58 DEBUG ==> Checking status with nodetool
UN  10.xx.xxx.xxx  1.98 GiB   256          10.0%             f05d0388-34a4-471a-9cf9-xxxxxxxxxx  rack1
cassandra 09:43:49.51 INFO  ==> Nodetool reported the successful startup of Cassandra
assandra 10:08:11.15 INFO  ==> Nodetool reported the successful startup of Cassandra
cassandra 10:08:11.16 INFO  ==> Trying to access CQL server @ ip-10-xx-xxx-xx
cassandra 10:08:11.17 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
Connection error: ('Unable to connect to any servers', {'10.xx.xxx.xxx': ConnectionShutdown('Connection to 10.xx.xxx.xxx was closed',)})
cassandra 10:09:06.82 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
Connection error: ('Unable to connect to any servers', {'10.xx.xxx.xxx': ConnectionShutdown('Connection to 10.xx.xxx.xxx was closed',)})
cassandra 10:10:02.53 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
Connection error: ('Unable to connect to any servers', {'10.xx.xxx.xxx': ConnectionShutdown('Connection to 10.xx.xxx.xxx was closed',)})
```
So, I got the log of **loading scripts from initdb.d** but didn't get the log of executing the file which is stated here - https://github.com/bitnami/bitnami-docker-cassandra/blob/a5e38cb4c253ada59f054d9009678a92b4333394/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L809

Is there any workaround or am I missing something here?

**Comment by ankitjain28may** [comment]
We are running Cassandra with clientEncryption set to true and hence during bootstrapping, the function `wait_for_cql_access` exits with code 1 due to ssl and fails to execute the custom script passed in the `/docker-entrypoint-initdb.d/`

**Comment by javsalgar** [comment]
Hi,

Do you have a minimal set of values that trigger the issue? I imagine you are using the chart.

**Comment by ankitjain28may** [comment]
hey, this issue with the SSL has been resolved after upgrading the Cassandra image to `3.11.11`. We were using the `3.11.6` image which doesn't have proper support for SSL during Cassandra bootstrap.

@migruiz4 Your solution worked perfectly for updating Cassandra config. Thanks
