### ISSUE TITLE
Mounting a volume with insufficient permissions doesn't report any error

### ISSUE THREAD

**Issue by EthanHaid** [bitnami/bitnami-docker-cassandra#96]
**Description**

Bitnami cassandra doesn't report a failure when a data persistence volume has the wrong permissions. This is especially inconvenient if the directory didn't already exist and is created by docker (the directory created has the wrong owner, and insufficient permissions)

**Steps to reproduce the issue:**

1. Ensure volume directory `./data` doesn't exist
2. Create image via docker-compose like so
```yaml
db:
    container_name: db
    image: bitnami/cassandra:latest
    volumes:
      - ./data:/bitnami/cassandra/data
    restart: always
    ports:
      - "9042:9042"
````

**Describe the results you received:**

The volume folder got created with insuffient permissions, and (more importantly) bitnami doesn't report the failure or how to fix it.

**Describe the results you expected:**

Ideally, the newly created folder would be owned by user 1001, or else inhearet the permissions/owner of the volume's parent directory.
At the least, CLI should report an issue with mounting the directory and stop the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Works great if I run `sudo chown 1001 ./data` though, it's just not clear that this is what I needed to do, and since git doesn't save file owner / perms, i need to run this every time i clone my repo.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 24.99GiB
 Name: docker-desktop
 ID: GAEK:EFAS:U2UT:2TNO:IWIJ:NAXN:V6IR:OT3B:DWUJ:3HCO:7W3E:KLP6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker-Desktop running in WSL2 Ubuntu 20.04

**Comment by marcosbc** [comment]
Hi @EthanHaid, you seem to be right. It just doesn't show any error. It seems like it would be possible to add some logic here using [`is_file_writable`](https://github.com/bitnami/bitnami-docker-cassandra/blob/master/4.0/debian-10/prebuildfs/opt/bitnami/scripts/libfs.sh#L86): https://github.com/bitnami/bitnami-docker-cassandra/blob/master/4.0/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L744

Since you reported this issue, would you be up to contributing the fix via a PR?

**Comment by marcosbc** [comment]
I don't think it's possible to get access to `chown` with root access. Instead, permissions would need to be set using a root container (meaning externally), due to how permissions work in Linux.

The only thing that we can do in a non-root container is to throw an error, as unfortunately a fix is not going to work. And my understanding from this issue is that the error is not happening due to the way we are starting Cassandra, right?

**Comment by EthanHaid** [comment]
yes, it's just a problem because the chown command needs root to run. I guess clearer language about that in [the docs](https://github.com/bitnami/bitnami-docker-cassandra/blob/master/README.md#persisting-your-application) would be good too.

**Comment by marcosbc** [comment]
Right now there is a note in the [Persisting your application section](https://github.com/bitnami/bitnami-docker-cassandra#persisting-your-application) like this:

> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID `1001`.

If you have any suggestions on how to improve that line, feel free to send a PR, we'd be happy to help with the review and release.
