### ISSUE TITLE
Update Java version in 4.x releases

### ISSUE THREAD

**Issue by tjdurham13** [bitnami/bitnami-docker-cassandra#97]
Looking at the new Official release Docker images for Cassandra, They have begun using JDK 11 [https://github.com/docker-library/cassandra/blob/f58183960ff693e4ec0c28f9f85453d69f646243/4.0/Dockerfile](url). It would be nice to have the bitnami Image updated to reflect Java 11 JDK and any startup parameter changes that came along with it.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this.
  I took a look and it seems that cassandra with java 11 is not recommended for production environments:
https://cassandra.apache.org/doc/latest/cassandra/new/java11.html
  It is strange that the official image uses something not recommended.

**Comment by tjdurham13** [comment]
I guess it would be appropriate to wait until they officially recommend java 11, or perhaps we create another image that can also build a java 11 build and just let it be know it's experimental?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but we don't have "experimental" images in our road map.
  Thanks for suggesting this, but we will wait until they recommend it.

**Comment by rafariossaa** [comment]
I am closing this issue.
In case it is necessary, you can post a comment and we will reopen it.
