### ISSUE TITLE
Drain Cassandra node when stopping 

### ISSUE THREAD

**Issue by a-nldisr** [bitnami/bitnami-docker-cassandra#99]
**Description**
Before stopping a Cassandra node it is advised to drain so that SSTables get flushed to disk and the node stops listening for new requests. 

**Feature request**
Before draining a Cassandra node it is advised to drain a node. Especially when performing upgrades. This is a nodetool command, see: https://cassandra.apache.org/doc/latest/cassandra/tools/nodetool/drain.html

I'm in doubt to either solve this in the docker image or in the helm chart for kubernetes. the `nodetool drain `command can either be placed in the helm chart as a `preStop` lifecycle object, but perhaps some scripting is required to capture the output from the drain command.

**Comment by juan131** [comment]
Hi @a-nldisr 

Thanks so much for this great suggestion!!  This is something to be solved in the Helm chart using a _preStop_ hook as you pointed out. Indeed, we're currently using the `nodetool decommission` command in the chart using this approach, see:

- [statefulset.yaml#L382](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/statefulset.yaml#L382)

> I'm in doubt to either solve this in the docker image or in the helm chart for kubernetes. the nodetool drain command can either be placed in the helm chart as a preStop lifecycle object, but perhaps some scripting is required to capture the output from the drain command.

In some images (such as Bitnami etcd container), we're including the scripts to be for health checks or lifecycle hooks in the image itself, see:

- [prestop.sh](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/etcd/prestop.sh)
- [healthcheck.sh](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/etcd/healthcheck.sh)

The, the chart simply needs to invoke these scripts:

- [statefulset.yaml#L246](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L246)
- [statefulset.yaml#L288](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L288)

We don't have a strong preference for using one approach or the other.
